
version: "3"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fsrxvcjbmtwaxt
      - POSTGRES_PASSWORD=fcd147ed2abf9e0910392a28cceddd55d7757c52a5edc2dff29d1e383333fdd1
      - POSTGRES_DB=d40guoc22hh35s
    volumes:
      - "./volumes/pg:/var/lib/postgresql/data"
  db_bank:
    build: .
    container_name: db_bank
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://database:123456@db:5432/db_db_bank
    command: node ./scripts/script.mjs