
version: "3"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vduimtittnfgbn
      - POSTGRES_PASSWORD=82202ab4c8e4602b4bb9d938f7da5f9f384085a5d0f1a9a8f94987126445d482
      - POSTGRES_DB=dpgdibc7i2q4d
    volumes:
      - "./volumes/pg:/var/lib/postgresql/data"
  db_bank:
    build: .
    container_name: db_bank
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://database:123456@db:5432/db_db_bank
    command: node ./scripts/script.mjs